# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - id: mainA
    env:
      - CGO_ENABLED=0
    main: mainA.go shared.go
    ldflags:
      - -X "main.version={{ .Version }}"
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx "{{ .Path }}"

env_files:
  github_token: ~/.config/goreleaser/github_token_custom

release:
  github:
    owner: sebbbastien
    name: goProgram

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
